load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "go_default_library",
    srcs = ["validator.go"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/github.com/opencontainers/runc/libcontainer/configs:go_default_library",
        "//src/github.com/opencontainers/runc/libcontainer/selinux:go_default_library",
    ],
)

go_test(
    name = "go_default_xtest",
    srcs = ["validator_test.go"],
    deps = [
        "//src/github.com/opencontainers/runc/libcontainer/configs:go_default_library",
        "//src/github.com/opencontainers/runc/libcontainer/configs/validate:go_default_library",
    ],
)
